# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "DevFest Levante 2018"
email: "info@devfestlevante.eu"
description: "Il summer camp dedicato agli sviluppatori ed agli interessati alle tecnologie Google organizzato dal GDG Bari"
baseurl: "/zeppelin"
url: "http//devfestlevante.eu"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-55641503-3"
googleAnalyticsSiteUrl: "devfestlevante.eu"
siteVerification: ""

# Organizer Info
organizerName: "GDG Bari"
organizerAlternateName: "Google Developer Group Bari"
organizerDescription: "Community aperta di volontari che condividono con passione esperienze sulle tecnologie Google."
organizerEmail: "info@devfestlevante.eu"
organizerLogo: "/img/seo/gdg-bari.png"
organizerLink: "http://devfestlevante.eu/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, machine learning, developers, bari, levante, salento, kotlin, tensorflow, dialogflow, angularjs"
twitterAccount: ""
socialImageSrcGooglePlus: ""
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: ""
c4sponsorsUrl: "https://goo.gl/forms/m6qICpojeed1bfr92"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 #- {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 #- {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {permalink: "/#tickets", text: "Prenota"}
rightNavigationButtons:
 - {permalink: "/#tickets", text: "Prenota"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest Levante 2018 "
eventDate: "25 Agosto - 1 Settembre, 2018"
typeoutTextValues: '"Salento", "Lu Mare", "Lu Sole", "Lu Sviluppo"'
typeoutFallback: "Season"
heroButtons:
 #- {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Prenota"}

# About Block
aboutTitle: "Il Summer Camp - Dev Side"
aboutBlock:
 - {title: "Workshops", image: "workshop.jpg", text: "Google Developer Expert e professionisti terranno 6 workshop durante le mattine su: Android e Kotlin, TensorFlow, Conversation Design, Angular, Firebase, Google Cloud. Ce n'è per tutti i gusti! " }
 - {title: "Talk", image: "conference.jpg", text: "Fantastici speaker: GDE e membri dei GDG di tutta Italia per apprendere nuove tecnologie e divertirsi" }
 - {title: "Hashcode", image: "hackathon.jpg", text: "Un problema reale e 4 ore per risolverlo in team, utilizzando la tua tecnologia preferita!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "60", specialCharacter: "+", info: "partecipanti", detail: "da tutta Italia"}
 - {count: "7", specialCharacter: "", info: "giorni", detail: "di tecnologie Google ed attività divertenti"}
 - {count: "14", specialCharacter: "+", info: "speaker", detail: "da tutto il Mediterraneo"}

# About Fun Block
aboutFunTitle: "Il Summer Camp - Funny Side"
aboutFunBlock:
 - {title: "Mare", image: "sea.jpg", text: "Scopri il bellissimo mare del salento" }
 - {title: "Divertimento", image: "enjoy.jpg", text: "Notte della taranta, festa in piscina, cena comunitaria e tanto altro ancora..." }
 - {title: "Tornei sportivi", image: "tournament.jpg", text: "Calcetto, ping pong, pallavolo, playstation. Accetti la sfida?" }

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Rockstar speaker"
rockstarSpeakersButtonText: "Vedi tutti gli speaker"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Village Camping Sentinella"
eventLocationLink: "https://www.campeggiosentinella.it/"
eventStreetAddress: "Via Degli Eucaliptus"
eventAddressLocality: "Torre Dell'Orso"
eventAddressLocalityRegion: "Lecce"
eventPostalCode: "73100"
eventAddressCountry: "Italia"
eventStartTime: ""
eventDoorTime: ""
eventEndTime: ""
eventPlaceCoordinates: "40.273107, 18.41815900000006"
mapCenterCoordinates: "40.273685, 18.41165"
mapMobileCenterCoordinates: "40.27260860000001, 18.42102909999994"

# Venue Block
venueBlockTitle: "Il Villaggio"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueTitle: "Sentinella"
venueFeatures: ["spazi workshop", "bungalow", "piscina e campi sportivi"]

# Tweets Feed Block
tweetsFeedImage: "feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest18 #dflev18"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizzatori"
partnersTitle: "Partner"
partnersC4sponsorsButton: "Diventa uno sponsor"

# Subscribe Block
#subscribeImage: "subscribe.jpg"
#subscribeTitle: "Subscribe for updates"
#subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
#subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Prezzi"
ticketsInfo: "La quota comprende posto in bungalow e partecipazione ai workshop ed alle attività comunitarie gratuite"
ticketsOffers:
 -
   name: "Bungalow da 2"
   price: "462"
   priceCurrency: "€"
   ticketsNumber: ""
   ribbon: ""
   buyButtonLink: ""
   buyButtonText: ""
   ticketContentList: ["Monolocale da 2 persone", "workshop", "Attività comunitarie"]
   validFrom: "2014-10-01T00:00"
   validThrough: "2014-10-23T23:59"
   soldOut: true
   soldOutText: "Sold Out"
 -
  name: "Posto letto in Bungalow da 4"
  price: "161"
  priceCurrency: "€"
  ticketsNumber: ""
  featured: true
  buyButtonLink: "https://goo.gl/forms/KVsStXjYEFwBBlYn1"
  buyButtonText: "Registrati"
  ticketContentList: ["Posto letto in monolocale da 4 condiviso", "workshop", "Attività comunitarie"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Bungalow da 4"
  price: "644"
  priceCurrency: "€"
  ticketsNumber: ""
  buyButtonLink: ""
  buyButtonText: ""
  additionalInfo: ""
  ticketContentList: ["Bilocale con 4 posti letto", "Workshop", "Attività comunitarie"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://t.me/joinchat/CaNX5khR0M7BrTugv5h8gw", icon: "telegram"}
# - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://facebook.com/GDGBari", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
  # - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contatti"
  links:
   - {link: "mailto:info@devfestlevante.eu", text: "info@devfestlevante.eu"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Codice di condotta"}

# Blog
blogTitle: "Ultime news"
blogCommentsEnabled: true
discusShortName: ""

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Siamo un gruppo di sviluppatori, designer e imprenditori che condividono la passione per le tecnologie Google"

# Logistics Find Way Block
findWayTitle: "Come arrivare"
findWayDistance: "Distanza"
findWayDriving: "In Macchina"
findWayWalking: "Camminando"
findWayBicycling: "In Bicicletta"
findWayTransit: "Transito"
findWayFindFlight: "Trova un volo"
logisticsMapCenterCoordinates: "40.2733415, 18.428505200000018"
logisticsMapMobileCenterCoordinates: "40.27260860000001, 18.42102909999994"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction.jpg"
directionDetailsTitle: "Get around Torre Dell'Orso"
directionDetailsCards:
 - {title: "Dagli aeroporti", information: "La società di autobus SITA SUD effettua la tratta aeroporto di Brindisi - Lecce Foro Boario (Stazione degli autobus). La tariffa è di 6,50€ e segue <a href='http://www.sitasudtrasporti.it/archivio/Download/corse/sitasud/Puglia/Bari/85a4f897-3517-423f-ae88-33ea7b7342ae_ORBA793-18A.pdf/0' target='blank'>questi orari</a>"}
 - {title: "Trasporti pubblici", information: "La società di autobus COTRAP con l'autobus 101 effettua la tratta Lecce Foro Boario (Stazione degli autobus) - Lecce Stazione dei treni - Torre Dell'Orso. Si scende all'Hotel Thalas vicino al Village Camping Sentinella <a href='http://www.provincia.le.it/documents/10716/edbbec03-63a3-4a23-933a-9f922dd1d9db' target='blank'>info qui</>"}
# - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "FAQ"
  subCards:
   #-
   # title: "Hotels"
   # links:
   #  - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
   #  - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
   #  - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
   #  - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   #-
   # title: "Registration"
   # links:
   #  - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
   #  - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
   #  - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
   #  - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   #-
   # title: "Attendance Details"
   # links:
   #  - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
   #  - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
   #  - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
   #  - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hashcode"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
